<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Action;

/**
 * Builder for model Action
 *
 * @see Action
 */
class ActionBuilder
{
    /**
     * @var Action
     */
    private $instance;

    private function __construct(Action $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new action Builder object.
     */
    public static function init(): self
    {
        return new self(new Action());
    }

    /**
     * Sets button field.
     */
    public function button(?string $value): self
    {
        $this->instance->setButton($value);
        return $this;
    }

    /**
     * Sets buttons field.
     */
    public function buttons(?array $value): self
    {
        $this->instance->setButtons($value);
        return $this;
    }

    /**
     * Sets sections field.
     */
    public function sections(?array $value): self
    {
        $this->instance->setSections($value);
        return $this;
    }

    /**
     * Initializes a new action object.
     */
    public function build(): Action
    {
        return CoreHelper::clone($this->instance);
    }
}
