<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Audio;

/**
 * Builder for model Audio
 *
 * @see Audio
 */
class AudioBuilder
{
    /**
     * @var Audio
     */
    private $instance;

    private function __construct(Audio $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new audio Builder object.
     */
    public static function init(): self
    {
        return new self(new Audio());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets link field.
     */
    public function link(?string $value): self
    {
        $this->instance->setLink($value);
        return $this;
    }

    /**
     * Initializes a new audio object.
     */
    public function build(): Audio
    {
        return CoreHelper::clone($this->instance);
    }
}
