<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Body;

/**
 * Builder for model Body
 *
 * @see Body
 */
class BodyBuilder
{
    /**
     * @var Body
     */
    private $instance;

    private function __construct(Body $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new body Builder object.
     */
    public static function init(string $text): self
    {
        return new self(new Body($text));
    }

    /**
     * Initializes a new body object.
     */
    public function build(): Body
    {
        return CoreHelper::clone($this->instance);
    }
}
