<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\BusinessProfile;

/**
 * Builder for model BusinessProfile
 *
 * @see BusinessProfile
 */
class BusinessProfileBuilder
{
    /**
     * @var BusinessProfile
     */
    private $instance;

    private function __construct(BusinessProfile $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new business profile Builder object.
     */
    public static function init(string $id, string $messagingProduct, string $address, string $description): self
    {
        return new self(new BusinessProfile($id, $messagingProduct, $address, $description));
    }

    /**
     * Sets vertical field.
     */
    public function vertical(?string $value): self
    {
        $this->instance->setVertical($value);
        return $this;
    }

    /**
     * Sets email field.
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets websites field.
     */
    public function websites(?array $value): self
    {
        $this->instance->setWebsites($value);
        return $this;
    }

    /**
     * Sets profile picture url field.
     */
    public function profilePictureUrl(?string $value): self
    {
        $this->instance->setProfilePictureUrl($value);
        return $this;
    }

    /**
     * Initializes a new business profile object.
     */
    public function build(): BusinessProfile
    {
        return CoreHelper::clone($this->instance);
    }
}
