<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Button;

/**
 * Builder for model Button
 *
 * @see Button
 */
class ButtonBuilder
{
    /**
     * @var Button
     */
    private $instance;

    private function __construct(Button $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new button Builder object.
     */
    public static function init(string $type): self
    {
        return new self(new Button($type));
    }

    /**
     * Sets title field.
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Initializes a new button object.
     */
    public function build(): Button
    {
        return CoreHelper::clone($this->instance);
    }
}
