<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\ButtonParameter;

/**
 * Builder for model ButtonParameter
 *
 * @see ButtonParameter
 */
class ButtonParameterBuilder
{
    /**
     * @var ButtonParameter
     */
    private $instance;

    private function __construct(ButtonParameter $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new button parameter Builder object.
     */
    public static function init(string $type): self
    {
        return new self(new ButtonParameter($type));
    }

    /**
     * Sets payload field.
     */
    public function payload(?string $value): self
    {
        $this->instance->setPayload($value);
        return $this;
    }

    /**
     * Sets text field.
     */
    public function text(?string $value): self
    {
        $this->instance->setText($value);
        return $this;
    }

    /**
     * Initializes a new button parameter object.
     */
    public function build(): ButtonParameter
    {
        return CoreHelper::clone($this->instance);
    }
}
