<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\DateTimeObject;

/**
 * Builder for model DateTimeObject
 *
 * @see DateTimeObject
 */
class DateTimeObjectBuilder
{
    /**
     * @var DateTimeObject
     */
    private $instance;

    private function __construct(DateTimeObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new date time object Builder object.
     */
    public static function init(string $fallbackValue): self
    {
        return new self(new DateTimeObject($fallbackValue));
    }

    /**
     * Sets day of week field.
     */
    public function dayOfWeek(?int $value): self
    {
        $this->instance->setDayOfWeek($value);
        return $this;
    }

    /**
     * Sets year field.
     */
    public function year(?int $value): self
    {
        $this->instance->setYear($value);
        return $this;
    }

    /**
     * Sets month field.
     */
    public function month(?int $value): self
    {
        $this->instance->setMonth($value);
        return $this;
    }

    /**
     * Sets day of month field.
     */
    public function dayOfMonth(?int $value): self
    {
        $this->instance->setDayOfMonth($value);
        return $this;
    }

    /**
     * Sets hour field.
     */
    public function hour(?int $value): self
    {
        $this->instance->setHour($value);
        return $this;
    }

    /**
     * Sets minute field.
     */
    public function minute(?int $value): self
    {
        $this->instance->setMinute($value);
        return $this;
    }

    /**
     * Sets calendar field.
     */
    public function calendar(?string $value): self
    {
        $this->instance->setCalendar($value);
        return $this;
    }

    /**
     * Initializes a new date time object object.
     */
    public function build(): DateTimeObject
    {
        return CoreHelper::clone($this->instance);
    }
}
