<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Document;

/**
 * Builder for model Document
 *
 * @see Document
 */
class DocumentBuilder
{
    /**
     * @var Document
     */
    private $instance;

    private function __construct(Document $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new document Builder object.
     */
    public static function init(): self
    {
        return new self(new Document());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets link field.
     */
    public function link(?string $value): self
    {
        $this->instance->setLink($value);
        return $this;
    }

    /**
     * Sets caption field.
     */
    public function caption(?string $value): self
    {
        $this->instance->setCaption($value);
        return $this;
    }

    /**
     * Sets filename field.
     */
    public function filename(?string $value): self
    {
        $this->instance->setFilename($value);
        return $this;
    }

    /**
     * Initializes a new document object.
     */
    public function build(): Document
    {
        return CoreHelper::clone($this->instance);
    }
}
