<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Footer;

/**
 * Builder for model Footer
 *
 * @see Footer
 */
class FooterBuilder
{
    /**
     * @var Footer
     */
    private $instance;

    private function __construct(Footer $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new footer Builder object.
     */
    public static function init(string $text): self
    {
        return new self(new Footer($text));
    }

    /**
     * Initializes a new footer object.
     */
    public function build(): Footer
    {
        return CoreHelper::clone($this->instance);
    }
}
