<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\GetBusinessProfileIDResponse;

/**
 * Builder for model GetBusinessProfileIDResponse
 *
 * @see GetBusinessProfileIDResponse
 */
class GetBusinessProfileIDResponseBuilder
{
    /**
     * @var GetBusinessProfileIDResponse
     */
    private $instance;

    private function __construct(GetBusinessProfileIDResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new get business profile idresponse Builder object.
     */
    public static function init(array $data): self
    {
        return new self(new GetBusinessProfileIDResponse($data));
    }

    /**
     * Initializes a new get business profile idresponse object.
     */
    public function build(): GetBusinessProfileIDResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
