<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\GetPhoneNumberByIDResponse;

/**
 * Builder for model GetPhoneNumberByIDResponse
 *
 * @see GetPhoneNumberByIDResponse
 */
class GetPhoneNumberByIDResponseBuilder
{
    /**
     * @var GetPhoneNumberByIDResponse
     */
    private $instance;

    private function __construct(GetPhoneNumberByIDResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new get phone number by idresponse Builder object.
     */
    public static function init(
        string $verifiedName,
        string $displayPhoneNumber,
        string $id,
        string $qualityRating
    ): self {
        return new self(new GetPhoneNumberByIDResponse($verifiedName, $displayPhoneNumber, $id, $qualityRating));
    }

    /**
     * Initializes a new get phone number by idresponse object.
     */
    public function build(): GetPhoneNumberByIDResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
