<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Document;
use WhatsAppCloudAPILib\Models\Header;
use WhatsAppCloudAPILib\Models\Image;
use WhatsAppCloudAPILib\Models\Video;

/**
 * Builder for model Header
 *
 * @see Header
 */
class HeaderBuilder
{
    /**
     * @var Header
     */
    private $instance;

    private function __construct(Header $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new header Builder object.
     */
    public static function init(string $type): self
    {
        return new self(new Header($type));
    }

    /**
     * Sets text field.
     */
    public function text(?string $value): self
    {
        $this->instance->setText($value);
        return $this;
    }

    /**
     * Sets video field.
     */
    public function video(?Video $value): self
    {
        $this->instance->setVideo($value);
        return $this;
    }

    /**
     * Sets image field.
     */
    public function image(?Image $value): self
    {
        $this->instance->setImage($value);
        return $this;
    }

    /**
     * Sets document field.
     */
    public function document(?Document $value): self
    {
        $this->instance->setDocument($value);
        return $this;
    }

    /**
     * Initializes a new header object.
     */
    public function build(): Header
    {
        return CoreHelper::clone($this->instance);
    }
}
