<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Action;
use WhatsAppCloudAPILib\Models\Body;
use WhatsAppCloudAPILib\Models\Footer;
use WhatsAppCloudAPILib\Models\Header;
use WhatsAppCloudAPILib\Models\Interactive;

/**
 * Builder for model Interactive
 *
 * @see Interactive
 */
class InteractiveBuilder
{
    /**
     * @var Interactive
     */
    private $instance;

    private function __construct(Interactive $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new interactive Builder object.
     */
    public static function init(Action $action, Body $body, string $type): self
    {
        return new self(new Interactive($action, $body, $type));
    }

    /**
     * Sets footer field.
     */
    public function footer(?Footer $value): self
    {
        $this->instance->setFooter($value);
        return $this;
    }

    /**
     * Sets header field.
     */
    public function header(?Header $value): self
    {
        $this->instance->setHeader($value);
        return $this;
    }

    /**
     * Initializes a new interactive object.
     */
    public function build(): Interactive
    {
        return CoreHelper::clone($this->instance);
    }
}
