<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Location;

/**
 * Builder for model Location
 *
 * @see Location
 */
class LocationBuilder
{
    /**
     * @var Location
     */
    private $instance;

    private function __construct(Location $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new location Builder object.
     */
    public static function init(string $latitude, string $longitude): self
    {
        return new self(new Location($latitude, $longitude));
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets address field.
     */
    public function address(?string $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Initializes a new location object.
     */
    public function build(): Location
    {
        return CoreHelper::clone($this->instance);
    }
}
