<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Name;

/**
 * Builder for model Name
 *
 * @see Name
 */
class NameBuilder
{
    /**
     * @var Name
     */
    private $instance;

    private function __construct(Name $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new name Builder object.
     */
    public static function init(string $formattedName): self
    {
        return new self(new Name($formattedName));
    }

    /**
     * Sets first name field.
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets last name field.
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets middle name field.
     */
    public function middleName(?string $value): self
    {
        $this->instance->setMiddleName($value);
        return $this;
    }

    /**
     * Sets suffix field.
     */
    public function suffix(?string $value): self
    {
        $this->instance->setSuffix($value);
        return $this;
    }

    /**
     * Sets prefix field.
     */
    public function prefix(?string $value): self
    {
        $this->instance->setPrefix($value);
        return $this;
    }

    /**
     * Initializes a new name object.
     */
    public function build(): Name
    {
        return CoreHelper::clone($this->instance);
    }
}
