<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Org;

/**
 * Builder for model Org
 *
 * @see Org
 */
class OrgBuilder
{
    /**
     * @var Org
     */
    private $instance;

    private function __construct(Org $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new org Builder object.
     */
    public static function init(): self
    {
        return new self(new Org());
    }

    /**
     * Sets company field.
     */
    public function company(?string $value): self
    {
        $this->instance->setCompany($value);
        return $this;
    }

    /**
     * Sets department field.
     */
    public function department(?string $value): self
    {
        $this->instance->setDepartment($value);
        return $this;
    }

    /**
     * Sets title field.
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Initializes a new org object.
     */
    public function build(): Org
    {
        return CoreHelper::clone($this->instance);
    }
}
