<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\PhoneObject;

/**
 * Builder for model PhoneObject
 *
 * @see PhoneObject
 */
class PhoneObjectBuilder
{
    /**
     * @var PhoneObject
     */
    private $instance;

    private function __construct(PhoneObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new phone object Builder object.
     */
    public static function init(): self
    {
        return new self(new PhoneObject());
    }

    /**
     * Sets phone field.
     */
    public function phone(?string $value): self
    {
        $this->instance->setPhone($value);
        return $this;
    }

    /**
     * Sets wa id field.
     */
    public function waId(?string $value): self
    {
        $this->instance->setWaId($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new phone object object.
     */
    public function build(): PhoneObject
    {
        return CoreHelper::clone($this->instance);
    }
}
