<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\RegisterPhoneRequest;

/**
 * Builder for model RegisterPhoneRequest
 *
 * @see RegisterPhoneRequest
 */
class RegisterPhoneRequestBuilder
{
    /**
     * @var RegisterPhoneRequest
     */
    private $instance;

    private function __construct(RegisterPhoneRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new register phone request Builder object.
     */
    public static function init(string $messagingProduct, string $pin): self
    {
        return new self(new RegisterPhoneRequest($messagingProduct, $pin));
    }

    /**
     * Initializes a new register phone request object.
     */
    public function build(): RegisterPhoneRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
