<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\ResponseMessage;

/**
 * Builder for model ResponseMessage
 *
 * @see ResponseMessage
 */
class ResponseMessageBuilder
{
    /**
     * @var ResponseMessage
     */
    private $instance;

    private function __construct(ResponseMessage $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new response message Builder object.
     */
    public static function init(string $id): self
    {
        return new self(new ResponseMessage($id));
    }

    /**
     * Initializes a new response message object.
     */
    public function build(): ResponseMessage
    {
        return CoreHelper::clone($this->instance);
    }
}
