<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Row;

/**
 * Builder for model Row
 *
 * @see Row
 */
class RowBuilder
{
    /**
     * @var Row
     */
    private $instance;

    private function __construct(Row $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new row Builder object.
     */
    public static function init(string $id, string $title): self
    {
        return new self(new Row($id, $title));
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new row object.
     */
    public function build(): Row
    {
        return CoreHelper::clone($this->instance);
    }
}
