<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Section;

/**
 * Builder for model Section
 *
 * @see Section
 */
class SectionBuilder
{
    /**
     * @var Section
     */
    private $instance;

    private function __construct(Section $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new section Builder object.
     */
    public static function init(): self
    {
        return new self(new Section());
    }

    /**
     * Sets title field.
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets rows field.
     */
    public function rows(?array $value): self
    {
        $this->instance->setRows($value);
        return $this;
    }

    /**
     * Initializes a new section object.
     */
    public function build(): Section
    {
        return CoreHelper::clone($this->instance);
    }
}
