<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\SendMessageResponse;

/**
 * Builder for model SendMessageResponse
 *
 * @see SendMessageResponse
 */
class SendMessageResponseBuilder
{
    /**
     * @var SendMessageResponse
     */
    private $instance;

    private function __construct(SendMessageResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new send message response Builder object.
     */
    public static function init(string $messagingProduct, array $contacts, array $messages): self
    {
        return new self(new SendMessageResponse($messagingProduct, $contacts, $messages));
    }

    /**
     * Initializes a new send message response object.
     */
    public function build(): SendMessageResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
