<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\SetTwoStepVerificationCodeRequest;

/**
 * Builder for model SetTwoStepVerificationCodeRequest
 *
 * @see SetTwoStepVerificationCodeRequest
 */
class SetTwoStepVerificationCodeRequestBuilder
{
    /**
     * @var SetTwoStepVerificationCodeRequest
     */
    private $instance;

    private function __construct(SetTwoStepVerificationCodeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new set two step verification code request Builder object.
     */
    public static function init(string $pin): self
    {
        return new self(new SetTwoStepVerificationCodeRequest($pin));
    }

    /**
     * Initializes a new set two step verification code request object.
     */
    public function build(): SetTwoStepVerificationCodeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
