<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Sticker;

/**
 * Builder for model Sticker
 *
 * @see Sticker
 */
class StickerBuilder
{
    /**
     * @var Sticker
     */
    private $instance;

    private function __construct(Sticker $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new sticker Builder object.
     */
    public static function init(): self
    {
        return new self(new Sticker());
    }

    /**
     * Sets link field.
     */
    public function link(?string $value): self
    {
        $this->instance->setLink($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Initializes a new sticker object.
     */
    public function build(): Sticker
    {
        return CoreHelper::clone($this->instance);
    }
}
