<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\SuccessResponse;

/**
 * Builder for model SuccessResponse
 *
 * @see SuccessResponse
 */
class SuccessResponseBuilder
{
    /**
     * @var SuccessResponse
     */
    private $instance;

    private function __construct(SuccessResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new success response Builder object.
     */
    public static function init(bool $success): self
    {
        return new self(new SuccessResponse($success));
    }

    /**
     * Initializes a new success response object.
     */
    public function build(): SuccessResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
