<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\UpdateBusinessProfileRequest;

/**
 * Builder for model UpdateBusinessProfileRequest
 *
 * @see UpdateBusinessProfileRequest
 */
class UpdateBusinessProfileRequestBuilder
{
    /**
     * @var UpdateBusinessProfileRequest
     */
    private $instance;

    private function __construct(UpdateBusinessProfileRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new update business profile request Builder object.
     */
    public static function init(string $messagingProduct): self
    {
        return new self(new UpdateBusinessProfileRequest($messagingProduct));
    }

    /**
     * Sets address field.
     */
    public function address(?string $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets vertical field.
     */
    public function vertical(?string $value): self
    {
        $this->instance->setVertical($value);
        return $this;
    }

    /**
     * Sets email field.
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets websites field.
     */
    public function websites(?array $value): self
    {
        $this->instance->setWebsites($value);
        return $this;
    }

    /**
     * Sets profile picture url field.
     */
    public function profilePictureUrl(?string $value): self
    {
        $this->instance->setProfilePictureUrl($value);
        return $this;
    }

    /**
     * Initializes a new update business profile request object.
     */
    public function build(): UpdateBusinessProfileRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
