<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\UploadMedia;

/**
 * Builder for model UploadMedia
 *
 * @see UploadMedia
 */
class UploadMediaBuilder
{
    /**
     * @var UploadMedia
     */
    private $instance;

    private function __construct(UploadMedia $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new upload media Builder object.
     */
    public static function init(string $id): self
    {
        return new self(new UploadMedia($id));
    }

    /**
     * Initializes a new upload media object.
     */
    public function build(): UploadMedia
    {
        return CoreHelper::clone($this->instance);
    }
}
