<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\UploadMediaRequest;

/**
 * Builder for model UploadMediaRequest
 *
 * @see UploadMediaRequest
 */
class UploadMediaRequestBuilder
{
    /**
     * @var UploadMediaRequest
     */
    private $instance;

    private function __construct(UploadMediaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new upload media request Builder object.
     */
    public static function init(string $messagingProduct, string $file, string $type): self
    {
        return new self(new UploadMediaRequest($messagingProduct, $file, $type));
    }

    /**
     * Initializes a new upload media request object.
     */
    public function build(): UploadMediaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
