<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\UrlObject;

/**
 * Builder for model UrlObject
 *
 * @see UrlObject
 */
class UrlObjectBuilder
{
    /**
     * @var UrlObject
     */
    private $instance;

    private function __construct(UrlObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new url object Builder object.
     */
    public static function init(): self
    {
        return new self(new UrlObject());
    }

    /**
     * Sets url field.
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new url object object.
     */
    public function build(): UrlObject
    {
        return CoreHelper::clone($this->instance);
    }
}
