<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\VerifyCodeRequest;

/**
 * Builder for model VerifyCodeRequest
 *
 * @see VerifyCodeRequest
 */
class VerifyCodeRequestBuilder
{
    /**
     * @var VerifyCodeRequest
     */
    private $instance;

    private function __construct(VerifyCodeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new verify code request Builder object.
     */
    public static function init(string $code): self
    {
        return new self(new VerifyCodeRequest($code));
    }

    /**
     * Initializes a new verify code request object.
     */
    public function build(): VerifyCodeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
