<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use WhatsAppCloudAPILib\Models\Video;

/**
 * Builder for model Video
 *
 * @see Video
 */
class VideoBuilder
{
    /**
     * @var Video
     */
    private $instance;

    private function __construct(Video $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new video Builder object.
     */
    public static function init(): self
    {
        return new self(new Video());
    }

    /**
     * Sets link field.
     */
    public function link(?string $value): self
    {
        $this->instance->setLink($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Initializes a new video object.
     */
    public function build(): Video
    {
        return CoreHelper::clone($this->instance);
    }
}
