<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Controllers;

use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Request\Parameters\TemplateParam;
use CoreInterfaces\Core\Request\RequestMethod;
use WhatsAppCloudAPILib\Exceptions\ApiException;
use WhatsAppCloudAPILib\Models\SetTwoStepVerificationCodeRequest;
use WhatsAppCloudAPILib\Models\SuccessResponse;

class TwoStepVerificationController extends BaseController
{
    /**
     * You are required to set up two-step verification for your phone number, as this provides an extra
     * layer of security to the business accounts. You can use this endpoint to change two-step
     * verification code associated with your account.
     * After you change the verification code, future requests like changing the name, must use the new
     * code.
     *
     * You set up two-factor verification and register a phone number in the same API call.
     *
     * @param string $phoneNumberID
     * @param SetTwoStepVerificationCodeRequest $body
     *
     * @return SuccessResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function setTwoStepVerificationCode(
        string $phoneNumberID,
        SetTwoStepVerificationCodeRequest $body
    ): SuccessResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/{Phone-Number-ID}')
            ->auth('global')
            ->parameters(
                TemplateParam::init('Phone-Number-ID', $phoneNumberID),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)
            );

        $_resHandler = $this->responseHandler()->type(SuccessResponse::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
