<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib;

use Core\ClientBuilder;
use Core\Request\Parameters\TemplateParam;
use Core\Utils\CoreHelper;
use Unirest\Configuration;
use Unirest\HttpClient;
use WhatsAppCloudAPILib\Controllers\BusinessProfilesController;
use WhatsAppCloudAPILib\Controllers\MediaController;
use WhatsAppCloudAPILib\Controllers\MessagesController;
use WhatsAppCloudAPILib\Controllers\PhoneNumbersController;
use WhatsAppCloudAPILib\Controllers\RegistrationController;
use WhatsAppCloudAPILib\Controllers\TwoStepVerificationController;
use WhatsAppCloudAPILib\Utils\CompatibilityConverter;

class WhatsAppCloudAPIClient implements ConfigurationInterface
{
    private $messages;

    private $registration;

    private $businessProfiles;

    private $media;

    private $phoneNumbers;

    private $twoStepVerification;

    private $bearerAuthManager;

    private $config;

    private $client;

    /**
     * @see WhatsAppCloudAPIClientBuilder::init()
     * @see WhatsAppCloudAPIClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->bearerAuthManager = new BearerAuthManager(
            $this->config['accessToken'] ?? ConfigurationDefaults::ACCESS_TOKEN
        );
        $this->client = ClientBuilder::init(new HttpClient(Configuration::init($this)))
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('APIMATIC 3.0')
            ->globalConfig($this->getGlobalConfiguration())
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::DEFAULT_)
            ->authManagers(['global' => $this->bearerAuthManager])
            ->build();
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return WhatsAppCloudAPIClientBuilder WhatsAppCloudAPIClientBuilder instance
     */
    public function toBuilder(): WhatsAppCloudAPIClientBuilder
    {
        return WhatsAppCloudAPIClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->version($this->getVersion())
            ->accessToken($this->bearerAuthManager->getAccessToken())
            ->httpCallback($this->config['httpCallback'] ?? null);
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    public function getVersion(): string
    {
        return $this->config['version'] ?? ConfigurationDefaults::VERSION;
    }

    public function getBearerAuthCredentials(): ?BearerAuthCredentials
    {
        return $this->bearerAuthManager;
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see WhatsAppCloudAPIClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see WhatsAppCloudAPIClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Messages Controller
     */
    public function getMessagesController(): MessagesController
    {
        if ($this->messages == null) {
            $this->messages = new MessagesController($this->client);
        }
        return $this->messages;
    }

    /**
     * Returns Registration Controller
     */
    public function getRegistrationController(): RegistrationController
    {
        if ($this->registration == null) {
            $this->registration = new RegistrationController($this->client);
        }
        return $this->registration;
    }

    /**
     * Returns Business Profiles Controller
     */
    public function getBusinessProfilesController(): BusinessProfilesController
    {
        if ($this->businessProfiles == null) {
            $this->businessProfiles = new BusinessProfilesController($this->client);
        }
        return $this->businessProfiles;
    }

    /**
     * Returns Media Controller
     */
    public function getMediaController(): MediaController
    {
        if ($this->media == null) {
            $this->media = new MediaController($this->client);
        }
        return $this->media;
    }

    /**
     * Returns Phone Numbers Controller
     */
    public function getPhoneNumbersController(): PhoneNumbersController
    {
        if ($this->phoneNumbers == null) {
            $this->phoneNumbers = new PhoneNumbersController($this->client);
        }
        return $this->phoneNumbers;
    }

    /**
     * Returns Two Step Verification Controller
     */
    public function getTwoStepVerificationController(): TwoStepVerificationController
    {
        if ($this->twoStepVerification == null) {
            $this->twoStepVerification = new TwoStepVerificationController($this->client);
        }
        return $this->twoStepVerification;
    }

    /**
     * Get the defined global configurations
     */
    private function getGlobalConfiguration(): array
    {
        return [TemplateParam::init('Version', $this->getVersion())->dontEncode()];
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP =
        [Environment::PRODUCTION => [Server::DEFAULT_ => 'https://graph.facebook.com/{Version}']];
}
